config/routes.rb
Rails.application.routes.draw do
  resources :stream_services
  resources :streams
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :stream_services
  has_many :streams, through: :stream_services
end

app/models/stream.rb
class Stream < ApplicationRecord
  has_many :stream_services
  has_many :services, through: :stream_services

  def self.search(search)
    where("title LIKE ? OR description LIKE ?",  "%#{search}%", "%#{search}%")

  end
end

app/models/stream_service.rb
class StreamService < ApplicationRecord
  belongs_to :stream
  belongs_to :service
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/controllers/stream_services_controller.rb
class StreamServicesController < ApplicationController
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  def index
    @streams = Stream.all
    if params[:search]
      @streams = Stream.search(params[:search]).order("created_at DESC")
      
    else
      @streams = Stream.all.order("created_at DESC")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/stream_services_helper.rb
module StreamServicesHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1>Please Search for a Stream:</h1>
    <%= form_tag(streams_path, method: "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Streams" %>
    <%= submit_tag "Search", name: nil %>
    <% end %>
    
    <%= yield %>

  </body>
</html>

app/views/streams/index.html.erb
<% if @streams.blank? %>
  <h4>There are no streams containing the terms <%= params[:search] %>.</h4>
<% elsif @streams.length < Stream.all.length %>

<h2>Here are your matching streams:</h2>
<ul>
  <% @streams.each do |stream| %>
  <li><%= link_to stream.title, stream.link %></li>
  <% end %>
</ul>
<% end %>